### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by vfilby** [Allen-Synthesis/EuroPi#107]
# Question

**Ask your question**
On the build I did the LEDs are very bright (used what I had on hand rather than ordering to spec).  I was thinking I should be able to tone them down by replacing the 4.7k resisters leading to each LED with something closer to 33k.

Is this a reasonable approach or would you recommend something else?

**Comment by roryjamesallen** [comment]
This would be the right solution, just increase the resistors going to each LED! Increasing will not be a problem at all, however you can't decrease the resistance or the LEDs may cause the output voltage to drop, preventing the calibration from being able to complete (and thus making output voltages inaccurate)
