### ISSUE TITLE
[Documentation Suggestion] Error in Cap ID in Build Instructions

### ISSUE THREAD

**Issue by bsom** [Allen-Synthesis/EuroPi#112]
# Documentation Suggestion

**Describe the issue or suggestion**  
https://github.com/Allen-Synthesis/EuroPi/blob/main/hardware/build_guide.md
"Solder the 100nF capacitors to the back (C8, C9)."
They are numbered C7 and C8 on the board, not C8 and C9

**Comment by roryjamesallen** [comment]
Good spot! I think this is a left over issue from changing around the labelling of all the components during the build guide improvement. I'll fix this asap!
