### ISSUE TITLE
[Documentation Suggestion] transistor discrepancy

### ISSUE THREAD

**Issue by mjaskula** [Allen-Synthesis/EuroPi#14]
# Documentation Suggestion

**Describe the issue or suggestion**  
In the BOM the transistor is described as PNP, but the link goes to an NPN transistor.

**Additional context**  
I don't have enough electronics savvy to know if this is ok, or not. But even if it is, in the interest of clear documentation, it should be consistent.

**Comment by roryjamesallen** [comment]
Definitely an error in the documentation, thanks for pointing it out!
