### ISSUE TITLE
[Project Suggestion] Debug Logging

### ISSUE THREAD

**Issue by mjaskula** [Allen-Synthesis/EuroPi#140]
# Project Suggestion

PR #139 added debug logging and log file rolling support to the cvrecorder script. We should consider adding logging support to the EuroPi library so that scrips do not need to implement this.

The primary needs of this feature would be:
- speed of the logging. Anything that isn't logging exceptions after a crash would need to be quick to avoid interfering with the running script.
- Space management. We only have so much room on the Pico, so no need to store excessive or irrelevant log data. The referenced PR achieved this via log file rolling.

**Comment by redoxcode** [comment]
Maybe we should also think about reducing erase/write cycles that wear out the memory.
I think it is about 100,000 write/erase cycles, so it should be fine.
But maybe we should try to not some how end up always stressing the same sector...
