### ISSUE TITLE
[Question / Request] Kicad version of the hardware design files

### ISSUE THREAD

**Issue by Didah** [Allen-Synthesis/EuroPi#145]
Does anyone have Kicad versions of the board/schematic files?

It might be a plus to add those to the project at some point, as Kicad is free and available for all major OSes, where DesignSpark seems to be windows only unless I'm missing something?

Another upside would be automated interactive BOM creation due to this wonderful plugin: https://github.com/openscopeproject/InteractiveHtmlBom - this could be a help for future builders!
See https://openscopeproject.org/InteractiveHtmlBomDemo/html/pic_programmer.html for an example of an interactive BOM extracted using the plugin.

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1003931/169397047-14d6ebab-1350-494f-9e25-5fee542f7e1f.png">

**Comment by roryjamesallen** [comment]
KiCad design files are available in #147 including an interactive BOM. The PR is likely to sit unapproved for some time until the design files can be tested with a new order, but the basics, including schematic, are now present
