### ISSUE TITLE
[Documentation Suggestion] Schematic inconsistency

### ISSUE THREAD

**Issue by mjaskula** [Allen-Synthesis/EuroPi#17]
# Documentation Suggestion

**Describe the issue or suggestion**  
The schematic shows 4.7uF capacitors on the output stages but that value of capacitor does not appear in the build guide or BOM. I didn't check the values of other components.

**Comment by roryjamesallen** [comment]
Ah yup, that's a good spot! I recently changed the output capacitors to 100nF because the higher default PWM frequency has allowed the cutoff to be higher. The schematic has been changed to match that change now!
