### ISSUE TITLE
[Bug Report] GitHub actions are using deprecated commands

### ISSUE THREAD

**Issue by mjaskula** [Allen-Synthesis/EuroPi#172]
Look at the details of a [github actions run](https://github.com/Allen-Synthesis/EuroPi/actions) after a recent commit.

For example, you will see deprecation warnings similar to this in the 'continuous-integration' build:
```The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

We update our actions to remove these warnings before the commands become fully depreciated. It is likely that these commands are actually used by modules that are actions use. It may just be a need to upgrade these modules.

Verify that there are no actions raising warnings.

**Comment by mjaskula** [comment]
Please do. I would appreciate an outside option.

**Comment by roryjamesallen** [comment]
I can't see those deprecation commands anymore if I look at the newest workflow log for a commit, potentially fixed? @mjaskula

**Comment by mjaskula** [comment]
I still see deprecation warnings, for example here:

https://github.com/Allen-Synthesis/EuroPi/actions/runs/7801048079

But they are not the same text as I quoted above:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by mjaskula** [comment]
Never mind, I found the old one too. I's under the step 'Get pip cache dir'

**Comment by chrisib** [comment]
I think I've made the necessary changes for this here: https://github.com/Allen-Synthesis/EuroPi/pull/385
