### ISSUE TITLE
[Hardware Issue / Project Suggestion] Increase threshold for digital input

### ISSUE THREAD

**Issue by redoxcode** [Allen-Synthesis/EuroPi#196]
# Hardware Issue: Increase threshold for digital input
This is a minor Issue, but should be addressed when a hardware revision is made:
The threshold for the digital input to read as high is about 0.8V with the current hardware.
This might cause accidental triggers when used with noisy or not perfect square eurorack signals (8-10V cv)

**Expected behavior**  
For eurorack levels it would be better if the threshold would be increased to something between 2.5 and 5V.

**Comment by roryjamesallen** [comment]
Yup, this is a very good point! For future hardware it will be higher.
For the current hardware you should be able to very easily hack the threshold to be higher too: By soldering a resistor from the cathode of D1 to ground you will create a potential divider on the input before it reaches the transistor. The input resistor is 100K, so a simple potential divider equation can be used to set your own input threshold.
| Added Resistor | New Threshold |
| ----------------- | ---------------- |
| 100k | 1.6V |
| 47k | 2.5V |
| 18K | 5.24V |

**Comment by roryjamesallen** [comment]
As this would break compatibility with DIY expanders and the current documentation, I'm going to mark as resolved and re-open/move to a new repository when one is made for the next major hardware iteration i.e. where incompatible changes can be made

**Comment by roryjamesallen** [comment]
> Can you explain how this would break compatibility with DIY expanders?

Although it is a very unlikely incompatibility, there is a chance that users will have developed expanders or other modules which rely on the digital input having such a low threshold.
For example, say a user had designed an expander that only used 3.3V logic, for which a 'high' signal of +3.3V would be more than enough to trigger the digital input, but then the hardware was changed to have a threshold of say 5V and their expander would no longer be able to trigger the digital input at all.

It is certainly a change that should be implemented in future hardware, but I believe implementing a non-compatible change to the hardware without a new version would be a mistake, and this change alone doesn't warrant an entirely new and theoretically incompatible hardware version of its own
