### ISSUE TITLE
[Project Suggestion] Update calibration routine and implementation

### ISSUE THREAD

**Issue by redoxcode** [Allen-Synthesis/EuroPi#211]
# Update calibration routine and implementation

As mentioned in other issues (e.g. https://github.com/Allen-Synthesis/EuroPi/issues/209) and the discord channel multiple times, the way the calibration works could be improved.
I hope we can use this issue to collect our ideas and requirements and maybe find a good solution together.

I will start with these points:
- As mentioned in (https://github.com/Allen-Synthesis/EuroPi/issues/209) calibration of ain should be at least 2 points (0V and 10V) with multiple samples to account for noise. Especially the 0V measurement will be influenced by noise as the noise can't occur symmetrical around 0 (no values below 0 possible)
- Maybe more people have voltage measurement equipment (multimeter) than rescission voltage sources. So maybe calibrate the outputs first and then use that for the input? Maybe don't use the output to calibrate the input or vice versa?
- Maybe have calibrate all outputs independently? I guess they use the same parts on most builds, but there can still be differences due to the tolerances of the parts or bad connections.

**Comment by redoxcode** [comment]
- Maybe we can/should add a compensation for the INL pattern (https://pico-adc.markomo.me/INL-DNL/#why-does-the-dnl-spike) of the ADC used for ain as discussed here: https://github.com/Allen-Synthesis/EuroPi/issues/214

**Comment by redoxcode** [comment]
After PR https://github.com/Allen-Synthesis/EuroPi/pull/232 2 point calibration should actually use 0V measurement...

**Comment by roryjamesallen** [comment]
I believe this has been fixed with both #232 and #212
