### ISSUE TITLE
ADC problem

### ISSUE THREAD

**Issue by georgestheking** [Allen-Synthesis/EuroPi#214]
The PICO is buggy and has limitation following PICO HARDWARE DATASHEET.
One idea will be to use an external ADC like the MCP3204.

Best regards

Georges

**Comment by redoxcode** [comment]
Can you elaborate on how 'the PICO is buggy'?

**Comment by georgestheking** [comment]
Hi,
A small problem for the ADC :
https://www.hackster.io/news/raspberry-pi-confirms-it-is-investigating-a-flaw-in-the-raspberry-pi-pico-rp2040-adc-95c393b55dfb

Best regards
Georges

Le mer. 11 janv. 2023 à 22:04, redoxcode ***@***.***> a
écrit :

**Comment by roryjamesallen** [comment]
I understand the limitations with the inbuilt ADC of the Pico, but it is really too late to fix this now with the current hardware! Future hardware will almost certainly have external ADCs to allow there to be more of them as well, so I'll mark this as closed but know that it's on the list for future hardware improvements!
