### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by roryjamesallen** [Allen-Synthesis/EuroPi#244]
# Bug Report

**Describe the bug**  
The [quantizer](https://github.com/Allen-Synthesis/EuroPi/blob/main/software/contrib/quantizer.py) script doesn't seem to work in continuous mode; even when set to Cont. a trigger is required before it will send any output

**Comment by awonak** [comment]
Make sure you hit the B1 when Cont. is dialed in which will set the mode state. Pressing B1 to set state was the part that wasn't obvious to me at first.

**Comment by roryjamesallen** [comment]
> Make sure you hit the B1 when Cont. is dialed in which will set the mode state. Pressing B1 to set state was the part that wasn't obvious to me at first.

That's what I get for not RTFM
I might make a PR with some UI changes to make that button 1 functionality more obvious, maybe a SELECT text above the button or something. It would be nice if it were intuitive without needing to know to press button 1 because I assumed it just wasn't working!
