### ISSUE TITLE
Pico W?

### ISSUE THREAD

**Issue by toneburst** [Allen-Synthesis/EuroPi#273]
More of a question than an issue really: is the RPi Pico W able to be used as a drop-in replacement for the non-W variant?

Obviously it would use more power, if so…

**Comment by toneburst** [comment]
Cool. Let me know how it goes!

I haven’t checked, but my suspicion is that the power requirements of the W variant may be significantly higher.

May or may not be a problem for the module’s transformer.

**Comment by roryjamesallen** [comment]
> More of a question than an issue really: is the RPi Pico W able to be used as a drop-in replacement for the non-W variant?
> 
> Obviously it would use more power, if so…

Yes, the Pico W can be used very safely as a drop in replacement for a normal Pico!

Although it might draw slightly more, the 5V regulator on the EuroPi is really an overkill solution, so even though the entire module only draws around 90mA from the +12V rail, the regulator is capable of more than *>500mA* so if the W really needs more it will still be available to it
