### ISSUE TITLE
[Documentation Suggestion] Firmware docstrings and automated docgen

### ISSUE THREAD

**Issue by awonak** [Allen-Synthesis/EuroPi#29]
Update the europi.py firmware file to document public api methods with proper Python docstrings. 

This will then enable us to be able to automated documentation generation tools like Sphinx and readthedocs.

**Comment by mjaskula** [comment]
I have this working in my fork, publishing to GitHub Pages: https://mjaskula.github.io/EuroPi/

remaining work:

- [ ] a nicer theme
- [ ] markdown support
- [ ] update code and docs with new EuroPi class
