### ISSUE TITLE
[Question / Request] Power

### ISSUE THREAD

**Issue by drsm79** [Allen-Synthesis/EuroPi#316]
# Question

Loving the Europi - it's great thinking of a new module configuration and having it running in an evening or two. Will be submitting for PR when fully debugged. 

One question - from observation it seems like the LEDs don't work when it's just the pico powered via USB (which makes sense). Is it OK to have the module plugged in to both the rack PSU and USB? I couldn't see a comment in the docs & wanted to check before frying things.

**Comment by roryjamesallen** [comment]
It's completely safe to use it with only USB power (although as you've found, using it this way means the inputs and outputs (and LEDs) won't work), only rack power, or USB and rack power. The module is completely protected for any combination.
