### ISSUE TITLE
turing_machine.md bug

### ISSUE THREAD

**Issue by RDFRIES** [Allen-Synthesis/EuroPi#392]
turingMachine.md says: 
cv5: pulse 2 & 4

SHOULD BE:
cv5: pulse 2 & 3

Because, that's whats in the code

**Comment by chrisib** [comment]
Both are actually saying the same thing. The code:
```
cv1 - pulse 1 (or config value cv1_pulse_bit)
cv2 - pulse 2 (or config value cv2_pulse_bit)
cv3 - pulse 4 (or config value cv3_pulse_bit)
cv4 - pulse cv1 & cv2
cv5 - pulse cv2 & cv3
cv6 - sequence out
```
The documentation:
```
- **cv1:** pulse 1
- **cv2:** pulse 2
- **cv3:** pulse 4
- **cv4:** pulse 1 & 2
- **cv5:** pulse 2 & 4
- **cv6:** sequence out
```

The markdown file is referring to `pulses`, but the comment in the code is referring to the CV outputs, which are not the same thing.  CV3 outputs Pulse 4, so the comment in the code about CV5 is correct: it outputs Pulse 2 and Pulse 4 (which are individually output on CV2 and CV3).
