### ISSUE TITLE
[Project Suggestion] Add support for alternative OLED pin configurations

### ISSUE THREAD

**Issue by roryjamesallen** [Allen-Synthesis/EuroPi#6]
# Project Suggestion

**Describe your suggestion or idea**  
The current PCBs only support one pin layout for the I2C bus of the OLED display, meaning that alternative displays using the same driver which may be more accessible to other customers cannot be used.
The PCB could contain some hardware to allow the pins to be switched for alternative layouts.

**Images**  
The Pi Hut OLED
![image](https://user-images.githubusercontent.com/79809962/143566181-8d260f31-264c-49c0-9534-4bf4176c30c6.png)

CPC OLED (theoretically compatible but alternate pin configuration)
![image](https://user-images.githubusercontent.com/79809962/143566501-0fcf8f82-2e64-4320-a2d6-12ea697c8ec3.png)

**Comment by roryjamesallen** [comment]
Currently pursuing two possible ways of addressing this issue; hardware switches to allow configuration when the module is assembled, and a software + hardware approach where the pins can be switched using signals from GPIOs. The second would use up more pins of the Pico, but would result in much less hardware clutter and a much easier process for a DIY user.

**Comment by roryjamesallen** [comment]
Further research shows only two common pin layouts exist for this OLED display, so a simpler approach is possible: A Hardware DIP switch and pull-up/down resistors.

#### The two potential pin layouts
![image](https://user-images.githubusercontent.com/79809962/143588417-014f176a-457e-4657-b4cd-60dcc8a0ed86.png)

#### Proposed hardware switching solution
![image](https://user-images.githubusercontent.com/79809962/143588546-f27028f6-f152-4e47-8f14-c4d441432281.png)

In mode 1 (The Pi Hut), the DIP switch would be set to on/on/off/off
In mode 2 (CPC, AliExpress), it would be off/off/on/on

This would allow the two different OLED configurations to be used easily, with only a quick change of the switch positions during assembly to allow it to work.

#### Potential issues with solution
In theory, due to user error or misunderstanding, incorrect signals could be sent to the OLED, however this should not be an issue as the I2C bus runs on 3.3V, so even if the power rail were connected to a data pin, no damage should be caused and the issue could be fixed with a simple switch change.

**Comment by roryjamesallen** [comment]
#### Illustration of proposed solution
![image](https://user-images.githubusercontent.com/79809962/143590751-029f6c6c-a314-42cd-86d7-e7a6e6ad2c7d.png)
DIP switch is situated underneath the OLED display to prevent accidental knocking of the switches during removal of the module, but switches would still be accessible with a pencil if required

**Comment by awonak** [comment]
Another option I've seen modules use is jumpers and shunts to change hardware configuration. However, this probably wouldn't fit on the jack PCB and would have to be on the pico PBC.

Here's an example of a module I recently build that uses jumpers and shunts (regretfully I don't have the schematics). Check out page 65:
https://zlobmodular.com/wp-content/uploads/2021/01/svf_6612_builddocs-compressed.pdf

**Comment by roryjamesallen** [comment]
> Another option I've seen modules use is jumpers and shunts to change hardware configuration. However, this probably wouldn't fit on the jack PCB and would have to be on the pico PBC.

Yup, I did consider using shunts and in many ways it would have been a cleaner approach, however there just isn't room on either PCB. The jack PCB doesn't have the vertical space between boards for a full jumper + shunt, and the pico PCB doesn't have the room around the existing traces and components

**Comment by roryjamesallen** [comment]
A sheepish reply to my above comment: There may in fact be a much simpler header and shunt solution which would fit, as the shunts are shorter than I previously calculated, allowing for them to be mounted on the jack PCB but facing towards the pico PCB.  
  
As the pins alternate in a certain way between the two configurations, a solution with only an 8 way 2 row header and 4 shunts should be possible, taking up minimal space and being easy to set for the user:  
  
![image](https://user-images.githubusercontent.com/79809962/143684099-a3cc8e14-acd8-49ae-9722-f917be9d0a38.png)

**Comment by roryjamesallen** [comment]
Implemented solution works on new PCBs, users can even make the bridge simply using solder, saving the cost of shunts/jumpers if appearance isn't the priority!

![PXL_20211211_141137654](https://user-images.githubusercontent.com/79809962/145679698-876a5d9a-fff8-41ff-8868-234a577bfd7b.jpg)  
  
![PXL_20211211_141142226](https://user-images.githubusercontent.com/79809962/145679699-49f6bc8f-86ef-4920-b6cc-8a7d289e0af1.jpg)
