### ISSUE TITLE
[Documentation Suggestion] Fix broken and non-relative links

### ISSUE THREAD

**Issue by mjaskula** [Allen-Synthesis/EuroPi#9]
# Documentation Suggestion

There are a couple broken links in the docs, which are both pointing to https://allensynthesis.co.uk/europi/europi-programming.html this page doesn't seem to exist. I assume that it has been replaced with https://github.com/Allen-Synthesis/EuroPi/blob/main/software/programming_instructions.md

In addition most of the links in the documentation are hardcoded to point to the main branch of the main EuroPi repo. This means that these links become incorrect when viewing the docs on branches and forks.

**Comment by roryjamesallen** [comment]
Excellent improvement, now merged!
